// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dugukostpkftuzhmggxm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR1Z3Vrb3N0cGtmdHV6aG1nZ3htIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNDY2MTQsImV4cCI6MjA2NTcyMjYxNH0._rzvF8yW3Jbz_2RppVw_0o2G7maZzDM7Zo7MpiKAQiw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);